WORKING_DIR: XXXXXXX
POST_TO_HDX: False

HDX:
  PERSONAL_API_KEY: XXXXXXXXXXXXXXX
  SCENARIO: coindre_model
  NUMBER_OF_DAYS: 14
GAMS:
  GAMS_PATH: XXXXXXXXXXXXXXX
  WARM_UP: 1
  REFINED_HYDRAULICS: 1
  FILTER_UC_SCHEDULE: 1
  LOCK_PRODUCTION_PLAN: 24
  MIP_GAP: 0.01
  RUN_ID: 0
  RUN_TIME_LIMIT: 10
  IDE: "%gams.ide% lo=%gams.lo% errorlog=%gams.errorlog% errmsg=1"
