WORKING_DIR: ENTER THE ABSOLUTE PATH TO THE DIRECTORY WHERE THE INPUT, OUTPUT AND EXCEL VISUALISATION FILE WILL BE STORED
POST_TO_HDX: False

HDX:
  PERSONAL_API_KEY: ENTER YOUR API KEY IN HERE
  SCENARIO: coindre_model
  NUMBER_OF_DAYS: 14
GAMS:
  GAMS_PATH: PUT THE GAMS.EXE ABSOLUTE PATH ON YOUR MACHINE IN HERE
  WARM_UP: 1
  REFINED_HYDRAULICS: 1
  FILTER_UC_SCHEDULE: 1
  LOCK_PRODUCTION_PLAN: 24
  MIP_GAP: 0.01
  RUN_ID: ENTER A RUN ID IN HERE
  RUN_TIME_LIMIT: 2000
  IDE: "%gams.ide% lo=%gams.lo% errorlog=%gams.errorlog% errmsg=1"
