WORKING_DIR: C:\Users\WH5939\Documents\runs_gams
POST_TO_HDX: False

HDX:
  PERSONAL_API_KEY: xxxxxx
  SCENARIO: coindre_model
  NUMBER_OF_DAYS: 14
GAMS:
  GAMS_PATH: C:\Gams\win64\28.1\gams.exe
  IDE: ide=%gams.ide% lo=%gams.lo% errorlog=%gams.errorlog% errmsg=1
  INFLOWS_FACTOR_GR: 1
  INFLOWS_FACTOR_PR: 1
  WARM_UP: 1
  REFINED_HYDRAULICS: 1
  FILTER_UC_SCHEDULE: 1
  LOCK_PRODUCTION_PLAN: 24
  MIP_GAP: 0.01
  RUN_NUM: 0
  RUN_TIME_LIMIT: 2000
